auctions/urls.py
from django.urls import path

from . import views

from django.conf.urls import url

app_name = "auctions"

urlpatterns = [
    path("", views.index, name="index"),
    path("home", views.home, name="home"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("cards", views.cards_view, name="cards"),
    path("add", views.add, name="add"),
    path("qr", views.qrcode, name="qr"),
    path("otp", views.validateOTP, name="otp"),
    path('chart', views.chartData, name="chart"),
    path("register", views.register, name="register"),
    # path('api', views.ChartData.as_view()),
    path("add_comment", views.add_comment, name="add_comment"),
    path("listing_details", views.listing_details_view, name="listing_details"),
    path("watchlist", views.watchlist_view, name="watchlist"),
    path("category_list", views.category_list, name="category_list"),
    path("category_list/<str:category>", views.category_list_redirect, name="category_list_redirect"),
    path("add_to_watchlist", views.add_to_watchlist, name="add_to_watchlist"),
    path("place_bid", views.place_bid, name="place_bid"),
    path("end_listing", views.end_listing, name="end_listing"),
    path("auctions_history", views.auctions_history, name="auctions_history"),
    path("delete_item_watchlist", views.delete_item_watchlist, name="delete_item_watchlist"),
    path("payment", views.payment, name="payment"),
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("auctions.urls")),
]

auctions/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, User


class User(AbstractUser):
    def __str__(self):
        return f"{self.first_name}"

class Item(models.Model): 
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="item_list")
    title = models.CharField(max_length=64)
    description = models.CharField(max_length=256, blank=True)
    img_url = models.CharField(max_length=256, blank=True)
    starting_bid = models.DecimalField(decimal_places=2, max_digits=8)
    category = models.CharField(max_length=24, default='No Category')
    status = models.BooleanField(default=True)
    def __str__(self):
        return f"{self.title}, {self.description}"

class ItemCategory(models.Model):
    name = models.CharField(max_length=24, blank=False)
    item = models.ForeignKey(Item, blank=True, on_delete=models.CASCADE, related_name="category_list")
    def __str__(self):
        return f"{self.name}"

class Bid(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_bids")
    amount = models.DecimalField(decimal_places=2, max_digits=8)
    items = models.ForeignKey(Item, on_delete=models.CASCADE, related_name="user_bid_items", blank=True)
    def __str__(self):
        return f"{self.amount}"
    
    def __unicode__(self):
        return u'%s %s' % (self.amount, self.items)
    
class ItemComment(models.Model):
    text = models.TextField(max_length=512, blank=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE, related_name="comments_list")
    author = models.ForeignKey(User, on_delete=models.CASCADE)

class Watchlist(models.Model):
    items = models.ForeignKey(Item, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='watchlist_list')

    def __str__(self):
        return f"{self.items}, {self.user}"

class Category(models.Model):
    name = models.CharField(max_length=24, blank=False)
    items = models.ManyToManyField(Item, blank=True, related_name="categories")

    def __str__(self):
        return f"{self.name}"

class AuctionHistory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="history_user")
    items = models.ForeignKey(Item, on_delete=models.CASCADE, related_name="items_auction_history")

    def __str__(self):
        return f"{self.user.first_name}, {self.items}"

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django import forms
import logging
from twilio.rest import Client
from rest_framework.views import APIView
from django.db import models
from django.views.generic import View
import razorpay
import statistics
import random
import qrcode
import segno
from auctions.fusioncharts import FusionCharts
from .models import User, Bid, Item, ItemComment, Watchlist, ItemCategory, AuctionHistory
from .utils import utility
import json
from django.http import JsonResponse
from rest_framework.views import APIView
from rest_framework.response import Response
from django.core import serializers
from django.contrib.auth.decorators import login_required

logger = logging.getLogger('mylogger')
#Define forms based on models4

otp = 0
user = ""
otp1 = ""
items_bids = ""


def home(request):
    return render(request, "auctions/home.html")

class HomeView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'auctions/chart.html')

# class ChartData(APIView):
#     authentication_classes = []
#     permission_classes = []
   
#     def get(self, request, format = None):
#         labels = [
#             '1',
#             '2', 
#             '3', 
#             '4', 
#             '5', 
#             '6', 
#             '7',
#             '8'
#             ]
#         chartLabel = "Price Prediction"
#         chartdata = ['1000', '1200', '1500', '1800', '2000', '2200', '2500', '5555']
#         data ={
#                      "labels":labels,
#                      "chartLabel":chartLabel,
#                      "chartdata":chartdata,
#              }
#         return Response(data)

class ItemForm(forms.ModelForm):
    class Meta:
        category_choices = [
            ('clothing', 'Clothing'),
            ('toys', 'Toys'),
            ('electronics', 'Electronics'),
            ('art','Art')
        ]
        model = Item
        fields = ['title', 'description', 'img_url', 'starting_bid', 'category']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control',
                                            'id': 'item_title',
                                            'placeholder': 'Item Title'}),
            'description': forms.TextInput(attrs={'class': 'form-control',
                                            'id': 'item_description',
                                            'placeholder': 'Item Description'}),
            'img_url': forms.TextInput(attrs={'class': 'form-control',
                                            'id': 'item_img_url',
                                            'placeholder': 'Image Url'}),
            'starting_bid': forms.NumberInput(attrs={'class': 'form-control',
                                            'id': 'item_starting_bid',
                                            'placeholder': 'Initial Bid'}),   
            'category': forms.Select(choices=category_choices)                                       
        }

class Comment(models.Model):
    comment = models.TextField(max_length=256)

class CommentForm(forms.Form):
    class Meta:
        model = Comment
        fields = ['comment']
        widgets = {
            'comment': forms.Textarea(attrs={
                 'class':"form-control",
                 'id':"textAreaComment",
                 'rows':"2", 'placeholder':"Type a comment"
            })
        }

def index(request):
    #Here in the index page we want to display all active auction listings.
    items = utility.get_items()
    distinct_users = utility.get_users_with_items()
    json_data = serializers.serialize("json", items)
    json_users = json.dumps(distinct_users)
    message=""
    if request.method == 'POST':        
        listing_title = str(request.POST.get("listing_title", False))
        item_ = Item.objects.filter(title=listing_title).get()
        user_ = User.objects.filter(username=request.user.username).get()
        #Search for item in watchlist
        search_item = Watchlist.objects.filter(items=item_, user=user_)
        if len(search_item)==0:
            message="Item added to watchlist"
            Watchlist(items=item_, user=user_).save()
        else:
            message="Item Has already been added to watchlist"
    context = {
        "json" : json_data,
        "users": json_users
    }
    
    if items != None:
        items_with_bids =  Item.objects.filter(user_bid_items__items__isnull=False).distinct()
        bids = []
        for item in items:
            if item in items_with_bids:
                bids.append(Bid.objects.filter(items=item).order_by('amount').last().amount)
            else:
                bids.append(item.starting_bid)
        logger.info(bids)
        items_bids = list(zip(items,bids))
        return render(request, "auctions/index.html",{
            "items":items,
            "items_bids":items_bids,
            "json":json_data,
            "json_users": json_users,
            "commentForm": CommentForm(),
            "message":message
        })
    else:
        logger.info("index get")
        return render(request, "auctions/index.html", {
            "items":items,
        })

def qrcode(request):
    return render(request, "auctions/qr.html")

def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        global user
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            rno = random.randint(100000, 999999)
            global otp
            otp = rno
            im = segno.make_qr("OTP :"+str(rno))
            im.save(r"auctions/static/qrimage/sai.svg", scale=2.4)
            return HttpResponseRedirect(reverse('auctions:qr'))
            
            # login(request, user)
            # return HttpResponseRedirect(reverse("auctions:index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })

    else:
        return render(request, "auctions/login.html")


def validateOTP(request):
    otp1 = request.POST["otp"]
    print(otp1)
    if otp1 == str(otp):
        login(request, user)
        return HttpResponseRedirect(reverse("auctions:index"))
    else:
        return render(request, "auctions/login.html", {
            "message": "Invalid otp and/or password."
            })



def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("auctions:index"))


def register(request):
    if request.method == "POST":
        commentForm = CommentForm(request.POST)
        # if commentForm.is_valid():
            #logger.infor(commentForm)

        # Ensure password matches confirmation
        password = request.POST["password"]
        username=request.POST["username"]
        email=request.POST["email"]
        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("auctions:login"))
    else:
        return render(request, "auctions/register.html")

def add(request):
    if request.method == 'GET':
        logger.info("Get add")
        return render(request, "auctions/add.html", {
            "new_form": ItemForm()
        })
    else:
        add_item_form = ItemForm(request.POST)
        if add_item_form.is_valid():
            item_title = add_item_form['title'].value()
            item_desc = add_item_form['description'].value()
            item_img_url = add_item_form['img_url'].value()
            item_str_bid = add_item_form['starting_bid'].value()
            item_cat = add_item_form['category'].value()
            
            #Register a new Item to the db
            new_item = Item(user=request.user, 
                            title=item_title,
                            description=item_desc,
                            img_url=item_img_url,
                            starting_bid=item_str_bid,
                            category=item_cat)
            if new_item != None:
                new_item.save()
                message = "Item successfully added to the db"

                #If the item was added successfully, then create a category with that item after making
                #sure it has not already been added.
                # Category.objects.filter(item=new_item)
                item_category = ItemCategory(name=item_cat, item=new_item)
                item_category.save()

            else:
                message = "Failure while saving to the db"
            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            return render(request, "auctions/add.html", {
            "new_form": ItemForm(),
            "message": "Invalid Data"
            })

def cards_view(request):
    user = User.objects.filter(username=request.user.username).first()
    # bid = Bid.objects.get(user=user)
    item = Item.objects.filter(user=user)[1]
    description = str(item.description)[0:40] + ".."
    return render(request, "auctions/cards.html", {
        "user":user,
        "item":item,
        "description": description
    })



def listing_details_view(request):
    #Get the listing's title to show on this page
    if request.method == 'POST':        
        listing_title = str(request.POST.get("listing_title", False))
        if (str(request.GET.get("message_bid"))):

auctions/templates/auctions/auctions_won.html
{% extends 'auctions/layout.html' %}
{% load static %}

{% block nav %}
<style>
  .ml-auto > li:hover {
    background-color: #6d6d6d5b;
    border-radius: 10px;
    
    opacity: 0.8;
  }
</style>
    <nav class="navbar navbar-light navbar-expand-lg fixed-top" style="background-color: #e3f2fd">
          <a class="navbar-brand" href="#">Three Brains</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <!-- <input class="form-control" id="myInput" type="text" placeholder="Search.." style="width: 40%;"> -->
            <ul class="navbar-nav ml-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'auctions:index' %}">Active Listings</a>
              </li>
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:add' %}">Add Item</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:watchlist' %}">Watchlist</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:auctions_history' %}">Auctions History</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:category_list' %}">Categories</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'auctions:logout' %}">Log Out</a>
            </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:register' %}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:category_list' %}">Categories</a>
                </li>
            {% endif %}
            </ul>
          </div>
        </nav>
{% endblock %}

{% block body %}

<div style="justify-content: center; display: flex; width:100%; margin-top: 60px; flex-direction: column; align-items: center;">
  <h1 style="text-align: center; color: #000;">Auctions You Have Won</h1>

  
<!-- <div style="background: url('https://media.giphy.com/media/5T06ftQWtCMy0XFaaI/giphy.gif'); 
position: fixed; width: 100%; height: 100%;"> -->
{% if message %}
<p>{{message}}</p>
{% endif %}
</div>

{% if items %}
<div class="container">
    <div class="row" style="margin-top: 20px;">
{% for item in items_bids %}
        <div class="col-lg-4">
            <div class="card" style="width: 18rem; background-color: #000;">
                <img class="card-img-top" style="height: 220px;" src="{{item.0.img_url}}" alt="Card image cap">
                <div class="card-body">
                  <h5 class="card-title">
                      <span style="color: #fff; display: block; overflow: hidden; white-space: nowrap; height: 23px; text-overflow: ellipsis;">
                        {{item.0.title}}
                      </span>
                  </h5>
                  <h6 class="card-subtitle mb-2 text" style="color: #fff;">{{ item.0.user.username }}</h6>
                    <p class="card-text">
                        <span id="item-title" style="display: block; overflow: hidden; white-space: nowrap; height: 23px; text-overflow: ellipsis;color: #fff;">
                           {{item.0.description}}
                        </span>
                    </p>
                  
                  <div style="flex-direction: row; " class="flexbox-container">
                    <label style="font-size: 20px; font-weight: bold; padding-right: 10px; color: #fff;">Bid</label>
                    <label style="font-size: 35px; color: #fff;">${{item.1.amount}}</label>
                  </div>
                  <div>
                    <form method="POST" action="{% url 'auctions:payment' %}">
                      {% csrf_token %}
                      <script
                        src="https://checkout.razorpay.com/v1/checkout.js"
                        data-key="rzp_test_11oVvfqFtEkl7O"
                        data-amount="{{item.1.amount}}"
                        data-currency="INR"
                        data-order_id="{{payment.id}}"
                        data-buttontext="Pay with Razorpay"
                        data-name="{{item.0.title}}"
                        data-description="{{item.0.description}}"
                        data-image="https://example.com/your_logo.jpg"
                        data-prefill.name="{{ item.0.user.username }}"
                        data-prefill.email="saikumar@gmail.com"
                        data-theme.color="#528FF0"></script>
                    </form>
                  </div>
                </div>
            </div>
        </div>
{% endfor %}

</div>
</div> 
{% else %}
  <h4>No Auctions</h4>
{% endif %}

</div>

{% endblock  %}

auctions/templates/auctions/listing_details.html
{% extends "auctions/layout.html"  %}
{% load static %}

{% block nav %}
<style>
  .ml-auto > li:hover {
    background-color: #6d6d6d5b;
    border-radius: 10px;
    
    opacity: 0.8;
  }
</style>
    <nav class="navbar navbar-light navbar-expand-lg fixed-top" style="background-color: #e3f2fd">
          <a class="navbar-brand" href="#">Three Brains</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <!-- <input class="form-control" id="myInput" type="text" placeholder="Search.." style="width: 40%;"> -->
            <ul class="navbar-nav ml-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'auctions:index' %}">Active Listings</a>
              </li>
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:add' %}">Add Item</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:watchlist' %}">Watchlist</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:auctions_history' %}">Auctions History</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:category_list' %}">Categories</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'auctions:logout' %}">Log Out</a>
            </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:register' %}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:category_list' %}">Categories</a>
                </li>
            {% endif %}
            </ul>
          </div>
        </nav>
{% endblock %}

{% block body %}

<div class="container-fluid " style="margin-top: 50px">
    <div class="row justify-content-md-center">
        <div class="col-lg-10">
            <div class="card" style="margin: 10px;">
                <img class="card-img-top" height="600px" src="{{item.img_url}}" alt="Card image cap">
                <div class="card-body">
                  <h5 class="card-title" style="font-size: 50px;">{{item.title}}</h5>
                 <div style="height:60px; overflow: auto;">
                    <h3 class="card-text">{{item.description}}.</h3>
                 </div>
                 <div>
                   <form method="POST" action="{% url 'auctions:place_bid' %}">
                     {% csrf_token %}
                     {% if item.status %}
                      <input name="new_bid" placeholder="Bid" type="number">
                      <input hidden name="listing_title" value="{{item.title}}" placeholder="">
                      <button href="#" id="myBtn" class="btn btn-primary">Place Bid</button>
                     {% endif %}

                   </form>
                 </div>
                  
                  <div style="flex-direction: row; " class="flexbox-container">
                    <label style="font-size: 20px; font-weight: bold; padding-right: 10px;">Bid</label>
                    {% if last_bid %}
                    <label style="font-size: 35px; ">${{last_bid}}</label>  
                    {% else %}
                    <label style="font-size: 35px; ">${{item.starting_bid}}</label>
                    {% endif %}
                  </div>
                  <h6 class="card-subtitle mb-2 text-muted"><span style="color: #000000;font-weight: bold;">added by : </span>{{owner.username}}</h6>
                  <div  style="flex-flow: row wrap; " class="flexbox-container">
                    <div class="row">
                      <label style="padding-left: 15px; font-size: 20px; font-weight: bold; ">Status</label>
                      {% if item.status %}
                      <div style="width: 20px; height: 20px; border-radius: 50%; border: 1px solid; background-color:green; opacity: 0.4; margin-top: 5px; margin-left: 10px;"></div>
                      {% else %}
                      <div style="width: 20px; height: 20px; border-radius: 50%; border: 1px solid; background-color:red; opacity: 0.4;"></div>
                      {% endif %}
                    </div>
                    {% if privilege %}
                    
                    <div>
                    <form action="{% url 'auctions:end_listing' %}" method="POST">
                      {%csrf_token%}
                      <input hidden name="listing_title" value="{{item.title}}">
                     <button  type="submit" class="btn btn-warning">Time up</button>
                    </form></div>

                    <div>
                      <form action="{% url 'auctions:chart' %}" method="POST">
                        {%csrf_token%}
                        <input hidden name="listing_title" value="{{item.title}}">
                       <button  type="submit" class="btn btn-warning">Predict Price</button>
                      </form>
                    </div>

                    {% endif %}
                    
                    <!-- {% if item.status %} -->
                    
                     <!-- {% endif %} -->
                  </div>
                  {% if message_bid %}
                    <p style="font-weight: bold; color: green;">{{message_bid}}</p>
                    {%else%}
                  {%endif%}
                </div>

                
                <div class="modal-body">
                  <h5>Comments</h5>

                  {% for comment in comments %}
                    
                    <div class="media-list">
                      <li class="media">
                          <a class="pull-left" href="#">
                             <img class="media-object rounded-circle" height="150px" src="{% static 'auctions/media/img.png'%}" alt="profile">
                          </a>
                          <div style="background-color: #E2E2E2; " class="media-body">
                              <div style="padding: 20px; " class="well well-lg">
                                  <h4 class="media-heading text-uppercase reviews">{{comment.author.username}}</h4>
                                  <ul class="media-date text-uppercase reviews ">
                                     <li>19</li>
                                     <li>05</li>
                                     <li>2021</li>
                                  </ul>
                                  <p class="media-comment">
                                     {{comment.text}}
                                  </p>
                              </div>
                          </div>
                      </li> 
                    </div>
                    {% empty %}
                      <h6>No comment has been added yet :C</h6>
                {% endfor %}
                </div> 

                 <form method="POST" action="{% url 'auctions:add_comment' %}">
                   {% csrf_token%}
                  <div class="form-group" style="padding: 20px;">
                    <label for="commentText">New comment</label>
                    <input hidden type="text" value="{{item.title}}" name="listing_title">
                    <input hidden type="text" value="{{owner.username}}" name="owner">
                    <textarea class="form-control" name="commentText" id="commentText" rows="3"></textarea>
                    <div style="text-align: right ;" >
                      <button class="btn btn-secondary" style="margin: 10px;">Add Comment</button>
                   </div>
                  </div> 
                 </form>                                                
                </div>
            </div>        
        </div>
    </div>
  </div>

{% endblock %}

auctions/templates/auctions/watchlist.html
{% extends 'auctions/layout.html' %}
{% load static %}

{% block nav %}
<style>
  .ml-auto > li:hover {
    background-color: #6d6d6d5b;
    border-radius: 10px;
    
    opacity: 0.8;
  }
</style>
    <nav class="navbar navbar-light navbar-expand-lg fixed-top" style="background-color: #e3f2fd">
          <a class="navbar-brand" href="#">Three Brains</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <!-- <input class="form-control" id="myInput" type="text" placeholder="Search.." style="width: 40%;"> -->
            <ul class="navbar-nav ml-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'auctions:index' %}">Active Listings</a>
              </li>
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:add' %}">Add Item</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:watchlist' %}">Watchlist</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:auctions_history' %}">Auctions History</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:category_list' %}">Categories</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'auctions:logout' %}">Log Out</a>
            </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:register' %}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:category_list' %}">Categories</a>
                </li>
            {% endif %}
            </ul>
          </div>
        </nav>
{% endblock %}

{% block body %}

<div style="padding: 30px; margin-top: 50px;">
    <table class="table table-light table-bordered table-hover">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Item Name</th>
            <th scope="col">Starting Bid</th>
            <th scope="col">Description</th>
            <th scope="col">Action</th>
          </tr>
        </thead>
        <tbody>
            {% for item in watchlist %}
          <tr>
            <th scope="row"><a href="{% url 'auctions:listing_details'%}?listing_title={{item.items.title}}">{{item.items.title}}</a></th>
            <td>{{item.items.starting_bid}}</td>
            <td>{{item.items.description}}</td>
            <td><form action="{% url 'auctions:delete_item_watchlist' %}" method="POST">
                {% csrf_token %}
                <input hidden name="listing_title" value="{{item.items.title}}"></input>
                <button type="submit" class="btn btn-primary">Delete</button>
            </form></td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
</div>

{% endblock  %}